name: My Fist Workflow

on : push

jobs:
    fist_job: 
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checkout@v4

        - name: welcome meassage
          run: echo "my fisrt github action job"

        - name: List files
          run: ls

        - name: Read file
          run: cat README.md