name: Generate ASCII Artwork

on : push

jobs:
  ascii_job: 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: List Repo Files
      run: ls -ltra

    - name: Excecuting the shell script
      run: ./ascii-script.sh



   # - name: List files
   #    run: ls

   # - name: Read file
   #   run: cat README.md    